//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 07:29:59 PM CST 
//


package com.welch.xml.object;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 */
@SuppressWarnings("restriction")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "schedtableOrSCHEDGROUPOrTABLEOrSMARTTABLE",
    "template"
})
@XmlRootElement(name = "DEFTABLE")
public class DEFTABLE {

    @XmlElements({
        @XmlElement(name = "SCHED_TABLE", type = SCHEDTABLE.class),
        @XmlElement(name = "SCHED_GROUP", type = SCHEDGROUP.class),
        @XmlElement(name = "TABLE", type = TABLE.class),
        @XmlElement(name = "SMART_TABLE", type = SMARTTABLE.class)
    })
    protected List<Object> schedtableOrSCHEDGROUPOrTABLEOrSMARTTABLE;
    @XmlElement(name = "TEMPLATE")
    protected List<TEMPLATE> template;

    /**
     * Gets the value of the schedtableOrSCHEDGROUPOrTABLEOrSMARTTABLE property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schedtableOrSCHEDGROUPOrTABLEOrSMARTTABLE property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSCHEDTABLEOrSCHEDGROUPOrTABLEOrSMARTTABLE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SCHEDTABLE }
     * {@link SCHEDGROUP }
     * {@link TABLE }
     * {@link SMARTTABLE }
     * 
     * 
     */
    public List<Object> getSCHEDTABLEOrSCHEDGROUPOrTABLEOrSMARTTABLE() {
        if (schedtableOrSCHEDGROUPOrTABLEOrSMARTTABLE == null) {
            schedtableOrSCHEDGROUPOrTABLEOrSMARTTABLE = new ArrayList<Object>();
        }
        return this.schedtableOrSCHEDGROUPOrTABLEOrSMARTTABLE;
    }

    /**
     * Gets the value of the template property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the template property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTEMPLATE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TEMPLATE }
     * 
     * 
     */
    public List<TEMPLATE> getTEMPLATE() {
        if (template == null) {
            template = new ArrayList<TEMPLATE>();
        }
        return this.template;
    }

}
