//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 07:29:59 PM CST 
//


package com.welch.xml.object;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 */
@SuppressWarnings("restriction")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tagnamesOrRULEBASEDCALENDARSOrINCONDOrOUTCONDOrAUTOEDITOrQUANTITATIVEOrCONTROLOrSHOUTOrSTEPRANGEOrONOrAUTOEDIT2"
})
@XmlRootElement(name = "JOB")
public class JOB {

    @XmlAttribute(name = "JOBNAME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String jobname;
    @XmlAttribute(name = "MEMNAME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String memname;
    @XmlAttribute(name = "GROUP")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String group;
    @XmlAttribute(name = "APPLICATION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String application;
    @XmlAttribute(name = "TASKTYPE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tasktype;
    @XmlAttribute(name = "AUTHOR")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String author;
    @XmlAttribute(name = "MEMLIB")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String memlib;
    @XmlAttribute(name = "CMDLINE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cmdline;
    @XmlAttribute(name = "NODEID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String nodeid;
    @XmlAttribute(name = "OWNER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String owner;
    @XmlAttribute(name = "MAXRERUN")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String maxrerun;
    @XmlAttribute(name = "TIMEFROM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String timefrom;
    @XmlAttribute(name = "TIMETO")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String timeto;
    @XmlAttribute(name = "TIMEZONE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String timezone;
    @XmlAttribute(name = "DUE_OUT")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String dueout;
    @XmlAttribute(name = "PRIORITY")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String priority;
    @XmlAttribute(name = "CRITICAL")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String critical;
    @XmlAttribute(name = "CYCLIC")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cyclic;
    @XmlAttribute(name = "CONFIRM")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String confirm;
    @XmlAttribute(name = "AUTOARCH")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String autoarch;
    @XmlAttribute(name = "INTERVAL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String interval;
    @XmlAttribute(name = "OVERLIB")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String overlib;
    @XmlAttribute(name = "MAXWAIT")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String maxwait;
    @XmlAttribute(name = "DESCRIPTION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String description;
    @XmlAttribute(name = "DOCMEM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String docmem;
    @XmlAttribute(name = "DOCLIB")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String doclib;
    @XmlAttribute(name = "DAYS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String days;
    @XmlAttribute(name = "DAYS_AND_OR")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String daysandor;
    @XmlAttribute(name = "WEEKDAYS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String weekdays;
    @XmlAttribute(name = "DATE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String date;
    @XmlAttribute(name = "DAYSCAL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String dayscal;
    @XmlAttribute(name = "WEEKSCAL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String weekscal;
    @XmlAttribute(name = "CONFCAL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String confcal;
    @XmlAttribute(name = "RETRO")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String retro;
    @XmlAttribute(name = "SHIFT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shift;
    @XmlAttribute(name = "SHIFTNUM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shiftnum;
    @XmlAttribute(name = "MAXDAYS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String maxdays;
    @XmlAttribute(name = "MAXRUNS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String maxruns;
    @XmlAttribute(name = "RERUNMEM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rerunmem;
    @XmlAttribute(name = "RETEN_DAYS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String retendays;
    @XmlAttribute(name = "RETEN_GEN")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String retengen;
    @XmlAttribute(name = "TASK_CLASS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String taskclass;
    @XmlAttribute(name = "PREV_DAY")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String prevday;
    @XmlAttribute(name = "IND_CYCLIC")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String indcyclic;
    @XmlAttribute(name = "TAG_RELATIONSHIP")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tagrelationship;
    @XmlAttribute(name = "RULE_BASED_CALENDAR_RELATIONSHIP")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rulebasedcalendarrelationship;
    @XmlAttribute(name = "SYSDB")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sysdb;
    @XmlAttribute(name = "PDSNAME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pdsname;
    @XmlAttribute(name = "MINIMUM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String minimum;
    @XmlAttribute(name = "CATEGORY")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String category;
    @XmlAttribute(name = "PREVENTNCT2")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String preventnct2;
    @XmlAttribute(name = "JAN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String jan;
    @XmlAttribute(name = "FEB")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String feb;
    @XmlAttribute(name = "MAR")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String mar;
    @XmlAttribute(name = "APR")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String apr;
    @XmlAttribute(name = "MAY")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String may;
    @XmlAttribute(name = "JUN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String jun;
    @XmlAttribute(name = "JUL")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String jul;
    @XmlAttribute(name = "AUG")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String aug;
    @XmlAttribute(name = "SEP")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sep;
    @XmlAttribute(name = "OCT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String oct;
    @XmlAttribute(name = "NOV")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nov;
    @XmlAttribute(name = "DEC")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dec;
    @XmlAttribute(name = "OPTION")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String option;
    @XmlAttribute(name = "PAR")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String par;
    @XmlAttribute(name = "FROM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String from;
    @XmlAttribute(name = "ADJUST_COND")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String adjustcond;
    @XmlAttribute(name = "JOBS_IN_GROUP")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String jobsingroup;
    @XmlAttribute(name = "LARGE_SIZE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String largesize;
    @XmlAttribute(name = "CREATION_USER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String creationuser;
    @XmlAttribute(name = "CREATION_DATE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String creationdate;
    @XmlAttribute(name = "CREATION_TIME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String creationtime;
    @XmlAttribute(name = "CHANGE_USERID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String changeuserid;
    @XmlAttribute(name = "CHANGE_DATE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String changedate;
    @XmlAttribute(name = "CHANGE_TIME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String changetime;
    @XmlAttribute(name = "JOB_RELEASE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String jobrelease;
    @XmlAttribute(name = "JOB_VERSION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String jobversion;
    @XmlAttribute(name = "JOBISN")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String jobisn;
    @XmlAttribute(name = "APPL_TYPE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String appltype;
    @XmlAttribute(name = "APPL_VER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String applver;
    @XmlAttribute(name = "APPL_FORM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String applform;
    @XmlAttribute(name = "CM_VER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cmver;
    @XmlAttribute(name = "MULTY_AGENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String multyagent;
    @XmlAttribute(name = "ACTIVE_FROM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String activefrom;
    @XmlAttribute(name = "ACTIVE_TILL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String activetill;
    @XmlAttribute(name = "SCHEDULING_ENVIRONMENT")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String schedulingenvironment;
    @XmlAttribute(name = "SYSTEM_AFFINITY")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String systemaffinity;
    @XmlAttribute(name = "REQUEST_NJE_NODE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String requestnjenode;
    @XmlAttribute(name = "INSTREAM_JCL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String instreamjcl;
    @XmlAttribute(name = "USE_INSTREAM_JCL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String useinstreamjcl;
    @XmlAttribute(name = "STAT_CAL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String statcal;
    @XmlAttribute(name = "DUE_OUT_DAYSOFFSET")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String dueoutdaysoffset;
    @XmlAttribute(name = "FROM_DAYSOFFSET")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fromdaysoffset;
    @XmlAttribute(name = "TO_DAYSOFFSET")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String todaysoffset;
    @XmlAttribute(name = "CYCLIC_TYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cyclictype;
    @XmlAttribute(name = "CYCLIC_TOLERANCE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cyclictolerance;
    @XmlAttribute(name = "CYCLIC_INTERVAL_SEQUENCE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cyclicintervalsequence;
    @XmlAttribute(name = "CYCLIC_TIMES_SEQUENCE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cyclictimessequence;
    @XmlAttribute(name = "PARENT_TABLE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String parenttable;
    @XmlElements({
        @XmlElement(name = "TAG_NAMES", type = TAGNAMES.class),
        @XmlElement(name = "RULE_BASED_CALENDARS", type = RULEBASEDCALENDARS.class),
        @XmlElement(name = "INCOND", type = INCOND.class),
        @XmlElement(name = "OUTCOND", type = OUTCOND.class),
        @XmlElement(name = "AUTOEDIT", type = AUTOEDIT.class),
        @XmlElement(name = "QUANTITATIVE", type = QUANTITATIVE.class),
        @XmlElement(name = "CONTROL", type = CONTROL.class),
        @XmlElement(name = "SHOUT", type = SHOUT.class),
        @XmlElement(name = "STEP_RANGE", type = STEPRANGE.class),
        @XmlElement(name = "ON", type = ON.class),
        @XmlElement(name = "AUTOEDIT2", type = AUTOEDIT2 .class)
    })
    protected List<Object> tagnamesOrRULEBASEDCALENDARSOrINCONDOrOUTCONDOrAUTOEDITOrQUANTITATIVEOrCONTROLOrSHOUTOrSTEPRANGEOrONOrAUTOEDIT2;

    /**
     * Gets the value of the jobname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJOBNAME() {
        return jobname;
    }

    /**
     * Sets the value of the jobname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJOBNAME(String value) {
        this.jobname = value;
    }

    /**
     * Gets the value of the memname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEMNAME() {
        return memname;
    }

    /**
     * Sets the value of the memname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEMNAME(String value) {
        this.memname = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGROUP() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGROUP(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLICATION() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLICATION(String value) {
        this.application = value;
    }

    /**
     * Gets the value of the tasktype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTASKTYPE() {
        return tasktype;
    }

    /**
     * Sets the value of the tasktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTASKTYPE(String value) {
        this.tasktype = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTHOR() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTHOR(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the memlib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEMLIB() {
        return memlib;
    }

    /**
     * Sets the value of the memlib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEMLIB(String value) {
        this.memlib = value;
    }

    /**
     * Gets the value of the cmdline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMDLINE() {
        return cmdline;
    }

    /**
     * Sets the value of the cmdline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMDLINE(String value) {
        this.cmdline = value;
    }

    /**
     * Gets the value of the nodeid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNODEID() {
        return nodeid;
    }

    /**
     * Sets the value of the nodeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNODEID(String value) {
        this.nodeid = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOWNER() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOWNER(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the maxrerun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAXRERUN() {
        if (maxrerun == null) {
            return "0";
        } else {
            return maxrerun;
        }
    }

    /**
     * Sets the value of the maxrerun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAXRERUN(String value) {
        this.maxrerun = value;
    }

    /**
     * Gets the value of the timefrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMEFROM() {
        return timefrom;
    }

    /**
     * Sets the value of the timefrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMEFROM(String value) {
        this.timefrom = value;
    }

    /**
     * Gets the value of the timeto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMETO() {
        return timeto;
    }

    /**
     * Sets the value of the timeto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMETO(String value) {
        this.timeto = value;
    }

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMEZONE() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMEZONE(String value) {
        this.timezone = value;
    }

    /**
     * Gets the value of the dueout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDUEOUT() {
        return dueout;
    }

    /**
     * Sets the value of the dueout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDUEOUT(String value) {
        this.dueout = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRIORITY() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRIORITY(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the critical property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRITICAL() {
        if (critical == null) {
            return "0";
        } else {
            return critical;
        }
    }

    /**
     * Sets the value of the critical property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRITICAL(String value) {
        this.critical = value;
    }

    /**
     * Gets the value of the cyclic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCYCLIC() {
        if (cyclic == null) {
            return "0";
        } else {
            return cyclic;
        }
    }

    /**
     * Sets the value of the cyclic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCYCLIC(String value) {
        this.cyclic = value;
    }

    /**
     * Gets the value of the confirm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFIRM() {
        if (confirm == null) {
            return "0";
        } else {
            return confirm;
        }
    }

    /**
     * Sets the value of the confirm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFIRM(String value) {
        this.confirm = value;
    }

    /**
     * Gets the value of the autoarch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTOARCH() {
        if (autoarch == null) {
            return "0";
        } else {
            return autoarch;
        }
    }

    /**
     * Sets the value of the autoarch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTOARCH(String value) {
        this.autoarch = value;
    }

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTERVAL() {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTERVAL(String value) {
        this.interval = value;
    }

    /**
     * Gets the value of the overlib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOVERLIB() {
        return overlib;
    }

    /**
     * Sets the value of the overlib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOVERLIB(String value) {
        this.overlib = value;
    }

    /**
     * Gets the value of the maxwait property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAXWAIT() {
        return maxwait;
    }

    /**
     * Sets the value of the maxwait property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAXWAIT(String value) {
        this.maxwait = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the docmem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCMEM() {
        return docmem;
    }

    /**
     * Sets the value of the docmem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCMEM(String value) {
        this.docmem = value;
    }

    /**
     * Gets the value of the doclib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCLIB() {
        return doclib;
    }

    /**
     * Sets the value of the doclib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCLIB(String value) {
        this.doclib = value;
    }

    /**
     * Gets the value of the days property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAYS() {
        return days;
    }

    /**
     * Sets the value of the days property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAYS(String value) {
        this.days = value;
    }

    /**
     * Gets the value of the daysandor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAYSANDOR() {
        if (daysandor == null) {
            return "OR";
        } else {
            return daysandor;
        }
    }

    /**
     * Sets the value of the daysandor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAYSANDOR(String value) {
        this.daysandor = value;
    }

    /**
     * Gets the value of the weekdays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWEEKDAYS() {
        return weekdays;
    }

    /**
     * Sets the value of the weekdays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWEEKDAYS(String value) {
        this.weekdays = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATE() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATE(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the dayscal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAYSCAL() {
        return dayscal;
    }

    /**
     * Sets the value of the dayscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAYSCAL(String value) {
        this.dayscal = value;
    }

    /**
     * Gets the value of the weekscal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWEEKSCAL() {
        return weekscal;
    }

    /**
     * Sets the value of the weekscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWEEKSCAL(String value) {
        this.weekscal = value;
    }

    /**
     * Gets the value of the confcal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFCAL() {
        return confcal;
    }

    /**
     * Sets the value of the confcal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFCAL(String value) {
        this.confcal = value;
    }

    /**
     * Gets the value of the retro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRETRO() {
        if (retro == null) {
            return "0";
        } else {
            return retro;
        }
    }

    /**
     * Sets the value of the retro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRETRO(String value) {
        this.retro = value;
    }

    /**
     * Gets the value of the shift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIFT() {
        return shift;
    }

    /**
     * Sets the value of the shift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIFT(String value) {
        this.shift = value;
    }

    /**
     * Gets the value of the shiftnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIFTNUM() {
        if (shiftnum == null) {
            return "+00";
        } else {
            return shiftnum;
        }
    }

    /**
     * Sets the value of the shiftnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIFTNUM(String value) {
        this.shiftnum = value;
    }

    /**
     * Gets the value of the maxdays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAXDAYS() {
        return maxdays;
    }

    /**
     * Sets the value of the maxdays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAXDAYS(String value) {
        this.maxdays = value;
    }

    /**
     * Gets the value of the maxruns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAXRUNS() {
        return maxruns;
    }

    /**
     * Sets the value of the maxruns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAXRUNS(String value) {
        this.maxruns = value;
    }

    /**
     * Gets the value of the rerunmem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRERUNMEM() {
        return rerunmem;
    }

    /**
     * Sets the value of the rerunmem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRERUNMEM(String value) {
        this.rerunmem = value;
    }

    /**
     * Gets the value of the retendays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRETENDAYS() {
        return retendays;
    }

    /**
     * Sets the value of the retendays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRETENDAYS(String value) {
        this.retendays = value;
    }

    /**
     * Gets the value of the retengen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRETENGEN() {
        return retengen;
    }

    /**
     * Sets the value of the retengen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRETENGEN(String value) {
        this.retengen = value;
    }

    /**
     * Gets the value of the taskclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTASKCLASS() {
        return taskclass;
    }

    /**
     * Sets the value of the taskclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTASKCLASS(String value) {
        this.taskclass = value;
    }

    /**
     * Gets the value of the prevday property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPREVDAY() {
        return prevday;
    }

    /**
     * Sets the value of the prevday property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPREVDAY(String value) {
        this.prevday = value;
    }

    /**
     * Gets the value of the indcyclic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINDCYCLIC() {
        return indcyclic;
    }

    /**
     * Sets the value of the indcyclic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINDCYCLIC(String value) {
        this.indcyclic = value;
    }

    /**
     * Gets the value of the tagrelationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAGRELATIONSHIP() {
        return tagrelationship;
    }

    /**
     * Sets the value of the tagrelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAGRELATIONSHIP(String value) {
        this.tagrelationship = value;
    }

    /**
     * Gets the value of the rulebasedcalendarrelationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRULEBASEDCALENDARRELATIONSHIP() {
        return rulebasedcalendarrelationship;
    }

    /**
     * Sets the value of the rulebasedcalendarrelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRULEBASEDCALENDARRELATIONSHIP(String value) {
        this.rulebasedcalendarrelationship = value;
    }

    /**
     * Gets the value of the sysdb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSYSDB() {
        if (sysdb == null) {
            return "0";
        } else {
            return sysdb;
        }
    }

    /**
     * Sets the value of the sysdb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSYSDB(String value) {
        this.sysdb = value;
    }

    /**
     * Gets the value of the pdsname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDSNAME() {
        return pdsname;
    }

    /**
     * Sets the value of the pdsname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDSNAME(String value) {
        this.pdsname = value;
    }

    /**
     * Gets the value of the minimum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMINIMUM() {
        return minimum;
    }

    /**
     * Sets the value of the minimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMINIMUM(String value) {
        this.minimum = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCATEGORY() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCATEGORY(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the preventnct2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPREVENTNCT2() {
        if (preventnct2 == null) {
            return "N";
        } else {
            return preventnct2;
        }
    }

    /**
     * Sets the value of the preventnct2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPREVENTNCT2(String value) {
        this.preventnct2 = value;
    }

    /**
     * Gets the value of the jan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJAN() {
        if (jan == null) {
            return "0";
        } else {
            return jan;
        }
    }

    /**
     * Sets the value of the jan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJAN(String value) {
        this.jan = value;
    }

    /**
     * Gets the value of the feb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFEB() {
        if (feb == null) {
            return "0";
        } else {
            return feb;
        }
    }

    /**
     * Sets the value of the feb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFEB(String value) {
        this.feb = value;
    }

    /**
     * Gets the value of the mar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAR() {
        if (mar == null) {
            return "0";
        } else {
            return mar;
        }
    }

    /**
     * Sets the value of the mar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAR(String value) {
        this.mar = value;
    }

    /**
     * Gets the value of the apr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPR() {
        if (apr == null) {
            return "0";
        } else {
            return apr;
        }
    }

    /**
     * Sets the value of the apr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPR(String value) {
        this.apr = value;
    }

    /**
     * Gets the value of the may property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAY() {
        if (may == null) {
            return "0";
        } else {
            return may;
        }
    }

    /**
     * Sets the value of the may property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAY(String value) {
        this.may = value;
    }

    /**
     * Gets the value of the jun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJUN() {
        if (jun == null) {
            return "0";
        } else {
            return jun;
        }
    }

    /**
     * Sets the value of the jun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJUN(String value) {
        this.jun = value;
    }

    /**
     * Gets the value of the jul property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJUL() {
        if (jul == null) {
            return "0";
        } else {
            return jul;
        }
    }

    /**
     * Sets the value of the jul property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJUL(String value) {
        this.jul = value;
    }

    /**
     * Gets the value of the aug property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUG() {
        if (aug == null) {
            return "0";
        } else {
            return aug;
        }
    }

    /**
     * Sets the value of the aug property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUG(String value) {
        this.aug = value;
    }

    /**
     * Gets the value of the sep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEP() {
        if (sep == null) {
            return "0";
        } else {
            return sep;
        }
    }

    /**
     * Sets the value of the sep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEP(String value) {
        this.sep = value;
    }

    /**
     * Gets the value of the oct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOCT() {
        if (oct == null) {
            return "0";
        } else {
            return oct;
        }
    }

    /**
     * Sets the value of the oct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOCT(String value) {
        this.oct = value;
    }

    /**
     * Gets the value of the nov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOV() {
        if (nov == null) {
            return "0";
        } else {
            return nov;
        }
    }

    /**
     * Sets the value of the nov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOV(String value) {
        this.nov = value;
    }

    /**
     * Gets the value of the dec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEC() {
        if (dec == null) {
            return "0";
        } else {
            return dec;
        }
    }

    /**
     * Sets the value of the dec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEC(String value) {
        this.dec = value;
    }

    /**
     * Gets the value of the option property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPTION() {
        return option;
    }

    /**
     * Sets the value of the option property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPTION(String value) {
        this.option = value;
    }

    /**
     * Gets the value of the par property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAR() {
        return par;
    }

    /**
     * Sets the value of the par property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAR(String value) {
        this.par = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFROM() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFROM(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the adjustcond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADJUSTCOND() {
        return adjustcond;
    }

    /**
     * Sets the value of the adjustcond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADJUSTCOND(String value) {
        this.adjustcond = value;
    }

    /**
     * Gets the value of the jobsingroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJOBSINGROUP() {
        return jobsingroup;
    }

    /**
     * Sets the value of the jobsingroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJOBSINGROUP(String value) {
        this.jobsingroup = value;
    }

    /**
     * Gets the value of the largesize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLARGESIZE() {
        return largesize;
    }

    /**
     * Sets the value of the largesize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLARGESIZE(String value) {
        this.largesize = value;
    }

    /**
     * Gets the value of the creationuser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATIONUSER() {
        return creationuser;
    }

    /**
     * Sets the value of the creationuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATIONUSER(String value) {
        this.creationuser = value;
    }

    /**
     * Gets the value of the creationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATIONDATE() {
        if (creationdate == null) {
            return "EMPTY";
        } else {
            return creationdate;
        }
    }

    /**
     * Sets the value of the creationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATIONDATE(String value) {
        this.creationdate = value;
    }

    /**
     * Gets the value of the creationtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATIONTIME() {
        if (creationtime == null) {
            return "EMPTY";
        } else {
            return creationtime;
        }
    }

    /**
     * Sets the value of the creationtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATIONTIME(String value) {
        this.creationtime = value;
    }

    /**
     * Gets the value of the changeuserid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHANGEUSERID() {
        return changeuserid;
    }

    /**
     * Sets the value of the changeuserid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHANGEUSERID(String value) {
        this.changeuserid = value;
    }

    /**
     * Gets the value of the changedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHANGEDATE() {
        return changedate;
    }

    /**
     * Sets the value of the changedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHANGEDATE(String value) {
        this.changedate = value;
    }

    /**
     * Gets the value of the changetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHANGETIME() {
        return changetime;
    }

    /**
     * Sets the value of the changetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHANGETIME(String value) {
        this.changetime = value;
    }

    /**
     * Gets the value of the jobrelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJOBRELEASE() {
        return jobrelease;
    }

    /**
     * Sets the value of the jobrelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJOBRELEASE(String value) {
        this.jobrelease = value;
    }

    /**
     * Gets the value of the jobversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJOBVERSION() {
        return jobversion;
    }

    /**
     * Sets the value of the jobversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJOBVERSION(String value) {
        this.jobversion = value;
    }

    /**
     * Gets the value of the jobisn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJOBISN() {
        return jobisn;
    }

    /**
     * Sets the value of the jobisn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJOBISN(String value) {
        this.jobisn = value;
    }

    /**
     * Gets the value of the appltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLTYPE() {
        return appltype;
    }

    /**
     * Sets the value of the appltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLTYPE(String value) {
        this.appltype = value;
    }

    /**
     * Gets the value of the applver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLVER() {
        return applver;
    }

    /**
     * Sets the value of the applver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLVER(String value) {
        this.applver = value;
    }

    /**
     * Gets the value of the applform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLFORM() {
        return applform;
    }

    /**
     * Sets the value of the applform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLFORM(String value) {
        this.applform = value;
    }

    /**
     * Gets the value of the cmver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMVER() {
        return cmver;
    }

    /**
     * Sets the value of the cmver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMVER(String value) {
        this.cmver = value;
    }

    /**
     * Gets the value of the multyagent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMULTYAGENT() {
        return multyagent;
    }

    /**
     * Sets the value of the multyagent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMULTYAGENT(String value) {
        this.multyagent = value;
    }

    /**
     * Gets the value of the activefrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTIVEFROM() {
        return activefrom;
    }

    /**
     * Sets the value of the activefrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTIVEFROM(String value) {
        this.activefrom = value;
    }

    /**
     * Gets the value of the activetill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTIVETILL() {
        return activetill;
    }

    /**
     * Sets the value of the activetill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTIVETILL(String value) {
        this.activetill = value;
    }

    /**
     * Gets the value of the schedulingenvironment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCHEDULINGENVIRONMENT() {
        return schedulingenvironment;
    }

    /**
     * Sets the value of the schedulingenvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCHEDULINGENVIRONMENT(String value) {
        this.schedulingenvironment = value;
    }

    /**
     * Gets the value of the systemaffinity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSYSTEMAFFINITY() {
        return systemaffinity;
    }

    /**
     * Sets the value of the systemaffinity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSYSTEMAFFINITY(String value) {
        this.systemaffinity = value;
    }

    /**
     * Gets the value of the requestnjenode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREQUESTNJENODE() {
        return requestnjenode;
    }

    /**
     * Sets the value of the requestnjenode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREQUESTNJENODE(String value) {
        this.requestnjenode = value;
    }

    /**
     * Gets the value of the instreamjcl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSTREAMJCL() {
        return instreamjcl;
    }

    /**
     * Sets the value of the instreamjcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSTREAMJCL(String value) {
        this.instreamjcl = value;
    }

    /**
     * Gets the value of the useinstreamjcl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSEINSTREAMJCL() {
        return useinstreamjcl;
    }

    /**
     * Sets the value of the useinstreamjcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSEINSTREAMJCL(String value) {
        this.useinstreamjcl = value;
    }

    /**
     * Gets the value of the statcal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATCAL() {
        return statcal;
    }

    /**
     * Sets the value of the statcal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATCAL(String value) {
        this.statcal = value;
    }

    /**
     * Gets the value of the dueoutdaysoffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDUEOUTDAYSOFFSET() {
        return dueoutdaysoffset;
    }

    /**
     * Sets the value of the dueoutdaysoffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDUEOUTDAYSOFFSET(String value) {
        this.dueoutdaysoffset = value;
    }

    /**
     * Gets the value of the fromdaysoffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFROMDAYSOFFSET() {
        return fromdaysoffset;
    }

    /**
     * Sets the value of the fromdaysoffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFROMDAYSOFFSET(String value) {
        this.fromdaysoffset = value;
    }

    /**
     * Gets the value of the todaysoffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTODAYSOFFSET() {
        return todaysoffset;
    }

    /**
     * Sets the value of the todaysoffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTODAYSOFFSET(String value) {
        this.todaysoffset = value;
    }

    /**
     * Gets the value of the cyclictype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCYCLICTYPE() {
        if (cyclictype == null) {
            return "Interval";
        } else {
            return cyclictype;
        }
    }

    /**
     * Sets the value of the cyclictype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCYCLICTYPE(String value) {
        this.cyclictype = value;
    }

    /**
     * Gets the value of the cyclictolerance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCYCLICTOLERANCE() {
        return cyclictolerance;
    }

    /**
     * Sets the value of the cyclictolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCYCLICTOLERANCE(String value) {
        this.cyclictolerance = value;
    }

    /**
     * Gets the value of the cyclicintervalsequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCYCLICINTERVALSEQUENCE() {
        return cyclicintervalsequence;
    }

    /**
     * Sets the value of the cyclicintervalsequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCYCLICINTERVALSEQUENCE(String value) {
        this.cyclicintervalsequence = value;
    }

    /**
     * Gets the value of the cyclictimessequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCYCLICTIMESSEQUENCE() {
        return cyclictimessequence;
    }

    /**
     * Sets the value of the cyclictimessequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCYCLICTIMESSEQUENCE(String value) {
        this.cyclictimessequence = value;
    }

    /**
     * Gets the value of the parenttable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARENTTABLE() {
        return parenttable;
    }

    /**
     * Sets the value of the parenttable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARENTTABLE(String value) {
        this.parenttable = value;
    }

    /**
     * Gets the value of the tagnamesOrRULEBASEDCALENDARSOrINCONDOrOUTCONDOrAUTOEDITOrQUANTITATIVEOrCONTROLOrSHOUTOrSTEPRANGEOrONOrAUTOEDIT2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tagnamesOrRULEBASEDCALENDARSOrINCONDOrOUTCONDOrAUTOEDITOrQUANTITATIVEOrCONTROLOrSHOUTOrSTEPRANGEOrONOrAUTOEDIT2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTAGNAMESOrRULEBASEDCALENDARSOrINCONDOrOUTCONDOrAUTOEDITOrQUANTITATIVEOrCONTROLOrSHOUTOrSTEPRANGEOrONOrAUTOEDIT2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TAGNAMES }
     * {@link RULEBASEDCALENDARS }
     * {@link INCOND }
     * {@link OUTCOND }
     * {@link AUTOEDIT }
     * {@link QUANTITATIVE }
     * {@link CONTROL }
     * {@link SHOUT }
     * {@link STEPRANGE }
     * {@link ON }
     * {@link AUTOEDIT2 }
     * 
     * 
     */
    public List<Object> getTAGNAMESOrRULEBASEDCALENDARSOrINCONDOrOUTCONDOrAUTOEDITOrQUANTITATIVEOrCONTROLOrSHOUTOrSTEPRANGEOrONOrAUTOEDIT2() {
        if (tagnamesOrRULEBASEDCALENDARSOrINCONDOrOUTCONDOrAUTOEDITOrQUANTITATIVEOrCONTROLOrSHOUTOrSTEPRANGEOrONOrAUTOEDIT2 == null) {
            tagnamesOrRULEBASEDCALENDARSOrINCONDOrOUTCONDOrAUTOEDITOrQUANTITATIVEOrCONTROLOrSHOUTOrSTEPRANGEOrONOrAUTOEDIT2 = new ArrayList<Object>();
        }
        return this.tagnamesOrRULEBASEDCALENDARSOrINCONDOrOUTCONDOrAUTOEDITOrQUANTITATIVEOrCONTROLOrSHOUTOrSTEPRANGEOrONOrAUTOEDIT2;
    }

}
