//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 07:29:59 PM CST 
//


package com.welch.xml.object;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@SuppressWarnings("restriction")
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DOFORCEJOB }
     * 
     */
    public DOFORCEJOB createDOFORCEJOB() {
        return new DOFORCEJOB();
    }

    /**
     * Create an instance of {@link DOMAIL }
     * 
     */
    public DOMAIL createDOMAIL() {
        return new DOMAIL();
    }

    /**
     * Create an instance of {@link RULEBASEDCALENDAR }
     * 
     */
    public RULEBASEDCALENDAR createRULEBASEDCALENDAR() {
        return new RULEBASEDCALENDAR();
    }

    /**
     * Create an instance of {@link OUTCOND }
     * 
     */
    public OUTCOND createOUTCOND() {
        return new OUTCOND();
    }

    /**
     * Create an instance of {@link DOCTBRULE }
     * 
     */
    public DOCTBRULE createDOCTBRULE() {
        return new DOCTBRULE();
    }

    /**
     * Create an instance of {@link SHOUT }
     * 
     */
    public SHOUT createSHOUT() {
        return new SHOUT();
    }

    /**
     * Create an instance of {@link DOAUTOEDIT }
     * 
     */
    public DOAUTOEDIT createDOAUTOEDIT() {
        return new DOAUTOEDIT();
    }

    /**
     * Create an instance of {@link DO }
     * 
     */
    public DO createDO() {
        return new DO();
    }

    /**
     * Create an instance of {@link DOTABLE }
     * 
     */
    public DOTABLE createDOTABLE() {
        return new DOTABLE();
    }

    /**
     * Create an instance of {@link STEPRANGE }
     * 
     */
    public STEPRANGE createSTEPRANGE() {
        return new STEPRANGE();
    }

    /**
     * Create an instance of {@link TABLE }
     * 
     */
    public TABLE createTABLE() {
        return new TABLE();
    }

    /**
     * Create an instance of {@link JOB }
     * 
     */
    public JOB createJOB() {
        return new JOB();
    }

    /**
     * Create an instance of {@link DOREMEDY }
     * 
     */
    public DOREMEDY createDOREMEDY() {
        return new DOREMEDY();
    }

    /**
     * Create an instance of {@link SCHEDGROUP }
     * 
     */
    public SCHEDGROUP createSCHEDGROUP() {
        return new SCHEDGROUP();
    }

    /**
     * Create an instance of {@link TAG }
     * 
     */
    public TAG createTAG() {
        return new TAG();
    }

    /**
     * Create an instance of {@link INCOND }
     * 
     */
    public INCOND createINCOND() {
        return new INCOND();
    }

    /**
     * Create an instance of {@link CONTROL }
     * 
     */
    public CONTROL createCONTROL() {
        return new CONTROL();
    }

    /**
     * Create an instance of {@link AUTOEDIT }
     * 
     */
    public AUTOEDIT createAUTOEDIT() {
        return new AUTOEDIT();
    }

    /**
     * Create an instance of {@link ONGROUP }
     * 
     */
    public ONGROUP createONGROUP() {
        return new ONGROUP();
    }

    /**
     * Create an instance of {@link SCHEDTABLE }
     * 
     */
    public SCHEDTABLE createSCHEDTABLE() {
        return new SCHEDTABLE();
    }

    /**
     * Create an instance of {@link QUANTITATIVE }
     * 
     */
    public QUANTITATIVE createQUANTITATIVE() {
        return new QUANTITATIVE();
    }

    /**
     * Create an instance of {@link DOIFRERUN }
     * 
     */
    public DOIFRERUN createDOIFRERUN() {
        return new DOIFRERUN();
    }

    /**
     * Create an instance of {@link TEMPLATE }
     * 
     */
    public TEMPLATE createTEMPLATE() {
        return new TEMPLATE();
    }

    /**
     * Create an instance of {@link TAGNAMES }
     * 
     */
    public TAGNAMES createTAGNAMES() {
        return new TAGNAMES();
    }

    /**
     * Create an instance of {@link RULEBASEDCALENDARS }
     * 
     */
    public RULEBASEDCALENDARS createRULEBASEDCALENDARS() {
        return new RULEBASEDCALENDARS();
    }

    /**
     * Create an instance of {@link ON }
     * 
     */
    public ON createON() {
        return new ON();
    }

    /**
     * Create an instance of {@link AUTOEDIT2 }
     * 
     */
    public AUTOEDIT2 createAUTOEDIT2() {
        return new AUTOEDIT2();
    }

    /**
     * Create an instance of {@link DOSHOUT }
     * 
     */
    public DOSHOUT createDOSHOUT() {
        return new DOSHOUT();
    }

    /**
     * Create an instance of {@link DOSYSOUT }
     * 
     */
    public DOSYSOUT createDOSYSOUT() {
        return new DOSYSOUT();
    }

    /**
     * Create an instance of {@link DOCOND }
     * 
     */
    public DOCOND createDOCOND() {
        return new DOCOND();
    }

    /**
     * Create an instance of {@link DOAUTOEDIT2 }
     * 
     */
    public DOAUTOEDIT2 createDOAUTOEDIT2() {
        return new DOAUTOEDIT2();
    }

    /**
     * Create an instance of {@link DEFTABLE }
     * 
     */
    public DEFTABLE createDEFTABLE() {
        return new DEFTABLE();
    }

    /**
     * Create an instance of {@link SMARTTABLE }
     * 
     */
    public SMARTTABLE createSMARTTABLE() {
        return new SMARTTABLE();
    }

    /**
     * Create an instance of {@link SUBTABLE }
     * 
     */
    public SUBTABLE createSUBTABLE() {
        return new SUBTABLE();
    }

    /**
     * Create an instance of {@link ONTABLE }
     * 
     */
    public ONTABLE createONTABLE() {
        return new ONTABLE();
    }

    /**
     * Create an instance of {@link DOGROUP }
     * 
     */
    public DOGROUP createDOGROUP() {
        return new DOGROUP();
    }

}
