//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 07:29:59 PM CST 
//


package com.welch.xml.object;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 */
@SuppressWarnings("restriction")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "doOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCTBRULEOrDOSYSOUTOrDOIFRERUNOrDOCONDOrDOMAILOrDOREMEDYOrDOAUTOEDIT2"
})
@XmlRootElement(name = "ON")
public class ON {

    @XmlAttribute(name = "STMT")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String stmt;
    @XmlAttribute(name = "CODE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String code;
    @XmlAttribute(name = "PGMS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pgms;
    @XmlAttribute(name = "PROCS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String procs;
    @XmlAttribute(name = "PATTERN")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pattern;
    @XmlAttribute(name = "FROM_COLUMN")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fromcolumn;
    @XmlAttribute(name = "TO_COLUMN")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tocolumn;
    @XmlAttribute(name = "AND_OR")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String andor;
    @XmlElements({
        @XmlElement(name = "DO", type = DO.class),
        @XmlElement(name = "DOAUTOEDIT", type = DOAUTOEDIT.class),
        @XmlElement(name = "DOSHOUT", type = DOSHOUT.class),
        @XmlElement(name = "DOFORCEJOB", type = DOFORCEJOB.class),
        @XmlElement(name = "DOCTBRULE", type = DOCTBRULE.class),
        @XmlElement(name = "DOSYSOUT", type = DOSYSOUT.class),
        @XmlElement(name = "DOIFRERUN", type = DOIFRERUN.class),
        @XmlElement(name = "DOCOND", type = DOCOND.class),
        @XmlElement(name = "DOMAIL", type = DOMAIL.class),
        @XmlElement(name = "DOREMEDY", type = DOREMEDY.class),
        @XmlElement(name = "DOAUTOEDIT2", type = DOAUTOEDIT2 .class)
    })
    protected List<Object> doOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCTBRULEOrDOSYSOUTOrDOIFRERUNOrDOCONDOrDOMAILOrDOREMEDYOrDOAUTOEDIT2;

    /**
     * Gets the value of the stmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTMT() {
        return stmt;
    }

    /**
     * Sets the value of the stmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTMT(String value) {
        this.stmt = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODE() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODE(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the pgms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPGMS() {
        return pgms;
    }

    /**
     * Sets the value of the pgms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPGMS(String value) {
        this.pgms = value;
    }

    /**
     * Gets the value of the procs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROCS() {
        return procs;
    }

    /**
     * Sets the value of the procs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROCS(String value) {
        this.procs = value;
    }

    /**
     * Gets the value of the pattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPATTERN() {
        return pattern;
    }

    /**
     * Sets the value of the pattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPATTERN(String value) {
        this.pattern = value;
    }

    /**
     * Gets the value of the fromcolumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFROMCOLUMN() {
        return fromcolumn;
    }

    /**
     * Sets the value of the fromcolumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFROMCOLUMN(String value) {
        this.fromcolumn = value;
    }

    /**
     * Gets the value of the tocolumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOCOLUMN() {
        return tocolumn;
    }

    /**
     * Sets the value of the tocolumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOCOLUMN(String value) {
        this.tocolumn = value;
    }

    /**
     * Gets the value of the andor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANDOR() {
        return andor;
    }

    /**
     * Sets the value of the andor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANDOR(String value) {
        this.andor = value;
    }

    /**
     * Gets the value of the doOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCTBRULEOrDOSYSOUTOrDOIFRERUNOrDOCONDOrDOMAILOrDOREMEDYOrDOAUTOEDIT2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the doOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCTBRULEOrDOSYSOUTOrDOIFRERUNOrDOCONDOrDOMAILOrDOREMEDYOrDOAUTOEDIT2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDOOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCTBRULEOrDOSYSOUTOrDOIFRERUNOrDOCONDOrDOMAILOrDOREMEDYOrDOAUTOEDIT2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DO }
     * {@link DOAUTOEDIT }
     * {@link DOSHOUT }
     * {@link DOFORCEJOB }
     * {@link DOCTBRULE }
     * {@link DOSYSOUT }
     * {@link DOIFRERUN }
     * {@link DOCOND }
     * {@link DOMAIL }
     * {@link DOREMEDY }
     * {@link DOAUTOEDIT2 }
     * 
     * 
     */
    public List<Object> getDOOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCTBRULEOrDOSYSOUTOrDOIFRERUNOrDOCONDOrDOMAILOrDOREMEDYOrDOAUTOEDIT2() {
        if (doOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCTBRULEOrDOSYSOUTOrDOIFRERUNOrDOCONDOrDOMAILOrDOREMEDYOrDOAUTOEDIT2 == null) {
            doOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCTBRULEOrDOSYSOUTOrDOIFRERUNOrDOCONDOrDOMAILOrDOREMEDYOrDOAUTOEDIT2 = new ArrayList<Object>();
        }
        return this.doOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCTBRULEOrDOSYSOUTOrDOIFRERUNOrDOCONDOrDOMAILOrDOREMEDYOrDOAUTOEDIT2;
    }

}
