//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 07:29:59 PM CST 
//


package com.welch.xml.object;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 */
@SuppressWarnings("restriction")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dogroupOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCONDOrDOMAILOrDOREMEDY"
})
@XmlRootElement(name = "ON_GROUP")
public class ONGROUP {

    @XmlAttribute(name = "CODE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String code;
    @XmlElements({
        @XmlElement(name = "DO_GROUP", type = DOGROUP.class),
        @XmlElement(name = "DOAUTOEDIT", type = DOAUTOEDIT.class),
        @XmlElement(name = "DOSHOUT", type = DOSHOUT.class),
        @XmlElement(name = "DOFORCEJOB", type = DOFORCEJOB.class),
        @XmlElement(name = "DOCOND", type = DOCOND.class),
        @XmlElement(name = "DOMAIL", type = DOMAIL.class),
        @XmlElement(name = "DOREMEDY", type = DOREMEDY.class)
    })
    protected List<Object> dogroupOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCONDOrDOMAILOrDOREMEDY;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODE() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODE(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the dogroupOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCONDOrDOMAILOrDOREMEDY property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dogroupOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCONDOrDOMAILOrDOREMEDY property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDOGROUPOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCONDOrDOMAILOrDOREMEDY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DOGROUP }
     * {@link DOAUTOEDIT }
     * {@link DOSHOUT }
     * {@link DOFORCEJOB }
     * {@link DOCOND }
     * {@link DOMAIL }
     * {@link DOREMEDY }
     * 
     * 
     */
    public List<Object> getDOGROUPOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCONDOrDOMAILOrDOREMEDY() {
        if (dogroupOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCONDOrDOMAILOrDOREMEDY == null) {
            dogroupOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCONDOrDOMAILOrDOREMEDY = new ArrayList<Object>();
        }
        return this.dogroupOrDOAUTOEDITOrDOSHOUTOrDOFORCEJOBOrDOCONDOrDOMAILOrDOREMEDY;
    }

}
