//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 07:29:59 PM CST 
//


package com.welch.xml.object;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@SuppressWarnings("restriction")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "QUANTITATIVE")
public class QUANTITATIVE {

    @XmlAttribute(name = "NAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "QUANT")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String quant;
    @XmlAttribute(name = "ONFAIL")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String onfail;
    @XmlAttribute(name = "ONOK")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String onok;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the quant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUANT() {
        if (quant == null) {
            return "1";
        } else {
            return quant;
        }
    }

    /**
     * Sets the value of the quant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUANT(String value) {
        this.quant = value;
    }

    /**
     * Gets the value of the onfail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getONFAIL() {
        return onfail;
    }

    /**
     * Sets the value of the onfail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setONFAIL(String value) {
        this.onfail = value;
    }

    /**
     * Gets the value of the onok property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getONOK() {
        return onok;
    }

    /**
     * Sets the value of the onok property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setONOK(String value) {
        this.onok = value;
    }

}
