//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 07:29:59 PM CST 
//


package com.welch.xml.object;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@SuppressWarnings("restriction")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "RULE_BASED_CALENDAR")
public class RULEBASEDCALENDAR {

    @XmlAttribute(name = "NAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "LEVEL")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String level;
    @XmlAttribute(name = "DAYS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String days;
    @XmlAttribute(name = "DAYS_AND_OR")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String daysandor;
    @XmlAttribute(name = "WEEKDAYS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String weekdays;
    @XmlAttribute(name = "DATE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String date;
    @XmlAttribute(name = "DAYSCAL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String dayscal;
    @XmlAttribute(name = "WEEKSCAL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String weekscal;
    @XmlAttribute(name = "CONFCAL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String confcal;
    @XmlAttribute(name = "RETRO")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String retro;
    @XmlAttribute(name = "SHIFT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shift;
    @XmlAttribute(name = "SHIFTNUM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shiftnum;
    @XmlAttribute(name = "MAXWAIT")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String maxwait;
    @XmlAttribute(name = "MAXRUNS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String maxruns;
    @XmlAttribute(name = "JAN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String jan;
    @XmlAttribute(name = "FEB")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String feb;
    @XmlAttribute(name = "MAR")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String mar;
    @XmlAttribute(name = "APR")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String apr;
    @XmlAttribute(name = "MAY")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String may;
    @XmlAttribute(name = "JUN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String jun;
    @XmlAttribute(name = "JUL")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String jul;
    @XmlAttribute(name = "AUG")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String aug;
    @XmlAttribute(name = "SEP")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sep;
    @XmlAttribute(name = "OCT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String oct;
    @XmlAttribute(name = "NOV")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nov;
    @XmlAttribute(name = "DEC")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dec;
    @XmlAttribute(name = "ACTIVE_FROM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String activefrom;
    @XmlAttribute(name = "ACTIVE_TILL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String activetill;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEVEL() {
        if (level == null) {
            return "TABLE";
        } else {
            return level;
        }
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEVEL(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the days property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAYS() {
        return days;
    }

    /**
     * Sets the value of the days property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAYS(String value) {
        this.days = value;
    }

    /**
     * Gets the value of the daysandor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAYSANDOR() {
        if (daysandor == null) {
            return "OR";
        } else {
            return daysandor;
        }
    }

    /**
     * Sets the value of the daysandor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAYSANDOR(String value) {
        this.daysandor = value;
    }

    /**
     * Gets the value of the weekdays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWEEKDAYS() {
        return weekdays;
    }

    /**
     * Sets the value of the weekdays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWEEKDAYS(String value) {
        this.weekdays = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATE() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATE(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the dayscal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAYSCAL() {
        return dayscal;
    }

    /**
     * Sets the value of the dayscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAYSCAL(String value) {
        this.dayscal = value;
    }

    /**
     * Gets the value of the weekscal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWEEKSCAL() {
        return weekscal;
    }

    /**
     * Sets the value of the weekscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWEEKSCAL(String value) {
        this.weekscal = value;
    }

    /**
     * Gets the value of the confcal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFCAL() {
        return confcal;
    }

    /**
     * Sets the value of the confcal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFCAL(String value) {
        this.confcal = value;
    }

    /**
     * Gets the value of the retro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRETRO() {
        if (retro == null) {
            return "0";
        } else {
            return retro;
        }
    }

    /**
     * Sets the value of the retro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRETRO(String value) {
        this.retro = value;
    }

    /**
     * Gets the value of the shift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIFT() {
        return shift;
    }

    /**
     * Sets the value of the shift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIFT(String value) {
        this.shift = value;
    }

    /**
     * Gets the value of the shiftnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIFTNUM() {
        if (shiftnum == null) {
            return "+00";
        } else {
            return shiftnum;
        }
    }

    /**
     * Sets the value of the shiftnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIFTNUM(String value) {
        this.shiftnum = value;
    }

    /**
     * Gets the value of the maxwait property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAXWAIT() {
        if (maxwait == null) {
            return "00";
        } else {
            return maxwait;
        }
    }

    /**
     * Sets the value of the maxwait property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAXWAIT(String value) {
        this.maxwait = value;
    }

    /**
     * Gets the value of the maxruns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAXRUNS() {
        return maxruns;
    }

    /**
     * Sets the value of the maxruns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAXRUNS(String value) {
        this.maxruns = value;
    }

    /**
     * Gets the value of the jan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJAN() {
        if (jan == null) {
            return "0";
        } else {
            return jan;
        }
    }

    /**
     * Sets the value of the jan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJAN(String value) {
        this.jan = value;
    }

    /**
     * Gets the value of the feb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFEB() {
        if (feb == null) {
            return "0";
        } else {
            return feb;
        }
    }

    /**
     * Sets the value of the feb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFEB(String value) {
        this.feb = value;
    }

    /**
     * Gets the value of the mar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAR() {
        if (mar == null) {
            return "0";
        } else {
            return mar;
        }
    }

    /**
     * Sets the value of the mar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAR(String value) {
        this.mar = value;
    }

    /**
     * Gets the value of the apr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPR() {
        if (apr == null) {
            return "0";
        } else {
            return apr;
        }
    }

    /**
     * Sets the value of the apr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPR(String value) {
        this.apr = value;
    }

    /**
     * Gets the value of the may property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAY() {
        if (may == null) {
            return "0";
        } else {
            return may;
        }
    }

    /**
     * Sets the value of the may property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAY(String value) {
        this.may = value;
    }

    /**
     * Gets the value of the jun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJUN() {
        if (jun == null) {
            return "0";
        } else {
            return jun;
        }
    }

    /**
     * Sets the value of the jun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJUN(String value) {
        this.jun = value;
    }

    /**
     * Gets the value of the jul property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJUL() {
        if (jul == null) {
            return "0";
        } else {
            return jul;
        }
    }

    /**
     * Sets the value of the jul property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJUL(String value) {
        this.jul = value;
    }

    /**
     * Gets the value of the aug property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUG() {
        if (aug == null) {
            return "0";
        } else {
            return aug;
        }
    }

    /**
     * Sets the value of the aug property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUG(String value) {
        this.aug = value;
    }

    /**
     * Gets the value of the sep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEP() {
        if (sep == null) {
            return "0";
        } else {
            return sep;
        }
    }

    /**
     * Sets the value of the sep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEP(String value) {
        this.sep = value;
    }

    /**
     * Gets the value of the oct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOCT() {
        if (oct == null) {
            return "0";
        } else {
            return oct;
        }
    }

    /**
     * Sets the value of the oct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOCT(String value) {
        this.oct = value;
    }

    /**
     * Gets the value of the nov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOV() {
        if (nov == null) {
            return "0";
        } else {
            return nov;
        }
    }

    /**
     * Sets the value of the nov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOV(String value) {
        this.nov = value;
    }

    /**
     * Gets the value of the dec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEC() {
        if (dec == null) {
            return "0";
        } else {
            return dec;
        }
    }

    /**
     * Sets the value of the dec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEC(String value) {
        this.dec = value;
    }

    /**
     * Gets the value of the activefrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTIVEFROM() {
        return activefrom;
    }

    /**
     * Sets the value of the activefrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTIVEFROM(String value) {
        this.activefrom = value;
    }

    /**
     * Gets the value of the activetill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTIVETILL() {
        return activetill;
    }

    /**
     * Sets the value of the activetill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTIVETILL(String value) {
        this.activetill = value;
    }

}
