//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 07:29:59 PM CST 
//


package com.welch.xml.object;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@SuppressWarnings("restriction")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "SHOUT")
public class SHOUT {

    @XmlAttribute(name = "WHEN", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String when;
    @XmlAttribute(name = "DEST", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String dest;
    @XmlAttribute(name = "URGENCY")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String urgency;
    @XmlAttribute(name = "MESSAGE", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String message;
    @XmlAttribute(name = "TIME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String time;
    @XmlAttribute(name = "DAYSOFFSET")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String daysoffset;

    /**
     * Gets the value of the when property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWHEN() {
        return when;
    }

    /**
     * Sets the value of the when property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWHEN(String value) {
        this.when = value;
    }

    /**
     * Gets the value of the dest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEST() {
        return dest;
    }

    /**
     * Sets the value of the dest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEST(String value) {
        this.dest = value;
    }

    /**
     * Gets the value of the urgency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURGENCY() {
        if (urgency == null) {
            return "R";
        } else {
            return urgency;
        }
    }

    /**
     * Sets the value of the urgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURGENCY(String value) {
        this.urgency = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMESSAGE() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMESSAGE(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIME() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIME(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the daysoffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAYSOFFSET() {
        return daysoffset;
    }

    /**
     * Sets the value of the daysoffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAYSOFFSET(String value) {
        this.daysoffset = value;
    }

}
