//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 07:29:59 PM CST 
//


package com.welch.xml.object;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@SuppressWarnings("restriction")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "STEP_RANGE")
public class STEPRANGE {

    @XmlAttribute(name = "NAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "FPGMS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fpgms;
    @XmlAttribute(name = "FPROCS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fprocs;
    @XmlAttribute(name = "TPGMS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tpgms;
    @XmlAttribute(name = "TPROCS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tprocs;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the fpgms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPGMS() {
        return fpgms;
    }

    /**
     * Sets the value of the fpgms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPGMS(String value) {
        this.fpgms = value;
    }

    /**
     * Gets the value of the fprocs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPROCS() {
        return fprocs;
    }

    /**
     * Sets the value of the fprocs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPROCS(String value) {
        this.fprocs = value;
    }

    /**
     * Gets the value of the tpgms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTPGMS() {
        return tpgms;
    }

    /**
     * Sets the value of the tpgms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTPGMS(String value) {
        this.tpgms = value;
    }

    /**
     * Gets the value of the tprocs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTPROCS() {
        return tprocs;
    }

    /**
     * Sets the value of the tprocs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTPROCS(String value) {
        this.tprocs = value;
    }

}
