//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 07:29:59 PM CST 
//


package com.welch.xml.object;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 */
@SuppressWarnings("restriction")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jobOrSUBTABLEOrRULEBASEDCALENDARSOrTAGNAMESOrINCONDOrOUTCONDOrCONTROLOrAUTOEDITOrONGROUPOrONTABLEOrSHOUTOrAUTOEDIT2"
})
@XmlRootElement(name = "SUB_TABLE")
public class SUBTABLE {

    @XmlAttribute(name = "JOBNAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String jobname;
    @XmlAttribute(name = "GROUP", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String group;
    @XmlAttribute(name = "APPLICATION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String application;
    @XmlAttribute(name = "AUTHOR")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String author;
    @XmlAttribute(name = "OWNER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String owner;
    @XmlAttribute(name = "TIMEFROM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String timefrom;
    @XmlAttribute(name = "TIMETO")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String timeto;
    @XmlAttribute(name = "DUE_OUT")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String dueout;
    @XmlAttribute(name = "TIMEZONE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String timezone;
    @XmlAttribute(name = "PRIORITY")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String priority;
    @XmlAttribute(name = "CONFIRM")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String confirm;
    @XmlAttribute(name = "DESCRIPTION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String description;
    @XmlAttribute(name = "DOCMEM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String docmem;
    @XmlAttribute(name = "DOCLIB")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String doclib;
    @XmlAttribute(name = "PREV_DAY")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String prevday;
    @XmlAttribute(name = "ADJUST_COND")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String adjustcond;
    @XmlAttribute(name = "CRITICAL")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String critical;
    @XmlAttribute(name = "CREATION_USER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String creationuser;
    @XmlAttribute(name = "CREATION_DATE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String creationdate;
    @XmlAttribute(name = "CREATION_TIME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String creationtime;
    @XmlAttribute(name = "CHANGE_USERID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String changeuserid;
    @XmlAttribute(name = "CHANGE_DATE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String changedate;
    @XmlAttribute(name = "CHANGE_TIME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String changetime;
    @XmlAttribute(name = "JOB_RELEASE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String jobrelease;
    @XmlAttribute(name = "JOB_VERSION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String jobversion;
    @XmlAttribute(name = "TABLE_ID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tableid;
    @XmlAttribute(name = "REAL_TABLEID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String realtableid;
    @XmlAttribute(name = "JOBISN")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String jobisn;
    @XmlAttribute(name = "LARGE_SIZE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String largesize;
    @XmlAttribute(name = "APPL_TYPE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String appltype;
    @XmlAttribute(name = "APPL_VER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String applver;
    @XmlAttribute(name = "APPL_FORM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String applform;
    @XmlAttribute(name = "CM_VER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cmver;
    @XmlElements({
        @XmlElement(name = "JOB", type = JOB.class),
        @XmlElement(name = "SUB_TABLE", type = SUBTABLE.class),
        @XmlElement(name = "RULE_BASED_CALENDARS", type = RULEBASEDCALENDARS.class),
        @XmlElement(name = "TAG_NAMES", type = TAGNAMES.class),
        @XmlElement(name = "INCOND", type = INCOND.class),
        @XmlElement(name = "OUTCOND", type = OUTCOND.class),
        @XmlElement(name = "CONTROL", type = CONTROL.class),
        @XmlElement(name = "AUTOEDIT", type = AUTOEDIT.class),
        @XmlElement(name = "ON_GROUP", type = ONGROUP.class),
        @XmlElement(name = "ON_TABLE", type = ONTABLE.class),
        @XmlElement(name = "SHOUT", type = SHOUT.class),
        @XmlElement(name = "AUTOEDIT2", type = AUTOEDIT2 .class)
    })
    protected List<Object> jobOrSUBTABLEOrRULEBASEDCALENDARSOrTAGNAMESOrINCONDOrOUTCONDOrCONTROLOrAUTOEDITOrONGROUPOrONTABLEOrSHOUTOrAUTOEDIT2;

    /**
     * Gets the value of the jobname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJOBNAME() {
        return jobname;
    }

    /**
     * Sets the value of the jobname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJOBNAME(String value) {
        this.jobname = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGROUP() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGROUP(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLICATION() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLICATION(String value) {
        this.application = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTHOR() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTHOR(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOWNER() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOWNER(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the timefrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMEFROM() {
        return timefrom;
    }

    /**
     * Sets the value of the timefrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMEFROM(String value) {
        this.timefrom = value;
    }

    /**
     * Gets the value of the timeto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMETO() {
        return timeto;
    }

    /**
     * Sets the value of the timeto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMETO(String value) {
        this.timeto = value;
    }

    /**
     * Gets the value of the dueout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDUEOUT() {
        return dueout;
    }

    /**
     * Sets the value of the dueout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDUEOUT(String value) {
        this.dueout = value;
    }

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMEZONE() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMEZONE(String value) {
        this.timezone = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRIORITY() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRIORITY(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the confirm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFIRM() {
        if (confirm == null) {
            return "0";
        } else {
            return confirm;
        }
    }

    /**
     * Sets the value of the confirm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFIRM(String value) {
        this.confirm = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the docmem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCMEM() {
        return docmem;
    }

    /**
     * Sets the value of the docmem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCMEM(String value) {
        this.docmem = value;
    }

    /**
     * Gets the value of the doclib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCLIB() {
        return doclib;
    }

    /**
     * Sets the value of the doclib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCLIB(String value) {
        this.doclib = value;
    }

    /**
     * Gets the value of the prevday property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPREVDAY() {
        return prevday;
    }

    /**
     * Sets the value of the prevday property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPREVDAY(String value) {
        this.prevday = value;
    }

    /**
     * Gets the value of the adjustcond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADJUSTCOND() {
        return adjustcond;
    }

    /**
     * Sets the value of the adjustcond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADJUSTCOND(String value) {
        this.adjustcond = value;
    }

    /**
     * Gets the value of the critical property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRITICAL() {
        if (critical == null) {
            return "0";
        } else {
            return critical;
        }
    }

    /**
     * Sets the value of the critical property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRITICAL(String value) {
        this.critical = value;
    }

    /**
     * Gets the value of the creationuser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATIONUSER() {
        return creationuser;
    }

    /**
     * Sets the value of the creationuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATIONUSER(String value) {
        this.creationuser = value;
    }

    /**
     * Gets the value of the creationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATIONDATE() {
        if (creationdate == null) {
            return "EMPTY";
        } else {
            return creationdate;
        }
    }

    /**
     * Sets the value of the creationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATIONDATE(String value) {
        this.creationdate = value;
    }

    /**
     * Gets the value of the creationtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATIONTIME() {
        if (creationtime == null) {
            return "EMPTY";
        } else {
            return creationtime;
        }
    }

    /**
     * Sets the value of the creationtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATIONTIME(String value) {
        this.creationtime = value;
    }

    /**
     * Gets the value of the changeuserid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHANGEUSERID() {
        return changeuserid;
    }

    /**
     * Sets the value of the changeuserid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHANGEUSERID(String value) {
        this.changeuserid = value;
    }

    /**
     * Gets the value of the changedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHANGEDATE() {
        return changedate;
    }

    /**
     * Sets the value of the changedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHANGEDATE(String value) {
        this.changedate = value;
    }

    /**
     * Gets the value of the changetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHANGETIME() {
        return changetime;
    }

    /**
     * Sets the value of the changetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHANGETIME(String value) {
        this.changetime = value;
    }

    /**
     * Gets the value of the jobrelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJOBRELEASE() {
        return jobrelease;
    }

    /**
     * Sets the value of the jobrelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJOBRELEASE(String value) {
        this.jobrelease = value;
    }

    /**
     * Gets the value of the jobversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJOBVERSION() {
        return jobversion;
    }

    /**
     * Sets the value of the jobversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJOBVERSION(String value) {
        this.jobversion = value;
    }

    /**
     * Gets the value of the tableid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTABLEID() {
        return tableid;
    }

    /**
     * Sets the value of the tableid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTABLEID(String value) {
        this.tableid = value;
    }

    /**
     * Gets the value of the realtableid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREALTABLEID() {
        return realtableid;
    }

    /**
     * Sets the value of the realtableid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREALTABLEID(String value) {
        this.realtableid = value;
    }

    /**
     * Gets the value of the jobisn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJOBISN() {
        return jobisn;
    }

    /**
     * Sets the value of the jobisn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJOBISN(String value) {
        this.jobisn = value;
    }

    /**
     * Gets the value of the largesize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLARGESIZE() {
        return largesize;
    }

    /**
     * Sets the value of the largesize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLARGESIZE(String value) {
        this.largesize = value;
    }

    /**
     * Gets the value of the appltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLTYPE() {
        return appltype;
    }

    /**
     * Sets the value of the appltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLTYPE(String value) {
        this.appltype = value;
    }

    /**
     * Gets the value of the applver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLVER() {
        return applver;
    }

    /**
     * Sets the value of the applver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLVER(String value) {
        this.applver = value;
    }

    /**
     * Gets the value of the applform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLFORM() {
        return applform;
    }

    /**
     * Sets the value of the applform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLFORM(String value) {
        this.applform = value;
    }

    /**
     * Gets the value of the cmver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMVER() {
        return cmver;
    }

    /**
     * Sets the value of the cmver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMVER(String value) {
        this.cmver = value;
    }

    /**
     * Gets the value of the jobOrSUBTABLEOrRULEBASEDCALENDARSOrTAGNAMESOrINCONDOrOUTCONDOrCONTROLOrAUTOEDITOrONGROUPOrONTABLEOrSHOUTOrAUTOEDIT2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobOrSUBTABLEOrRULEBASEDCALENDARSOrTAGNAMESOrINCONDOrOUTCONDOrCONTROLOrAUTOEDITOrONGROUPOrONTABLEOrSHOUTOrAUTOEDIT2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJOBOrSUBTABLEOrRULEBASEDCALENDARSOrTAGNAMESOrINCONDOrOUTCONDOrCONTROLOrAUTOEDITOrONGROUPOrONTABLEOrSHOUTOrAUTOEDIT2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JOB }
     * {@link SUBTABLE }
     * {@link RULEBASEDCALENDARS }
     * {@link TAGNAMES }
     * {@link INCOND }
     * {@link OUTCOND }
     * {@link CONTROL }
     * {@link AUTOEDIT }
     * {@link ONGROUP }
     * {@link ONTABLE }
     * {@link SHOUT }
     * {@link AUTOEDIT2 }
     * 
     * 
     */
    public List<Object> getJOBOrSUBTABLEOrRULEBASEDCALENDARSOrTAGNAMESOrINCONDOrOUTCONDOrCONTROLOrAUTOEDITOrONGROUPOrONTABLEOrSHOUTOrAUTOEDIT2() {
        if (jobOrSUBTABLEOrRULEBASEDCALENDARSOrTAGNAMESOrINCONDOrOUTCONDOrCONTROLOrAUTOEDITOrONGROUPOrONTABLEOrSHOUTOrAUTOEDIT2 == null) {
            jobOrSUBTABLEOrRULEBASEDCALENDARSOrTAGNAMESOrINCONDOrOUTCONDOrCONTROLOrAUTOEDITOrONGROUPOrONTABLEOrSHOUTOrAUTOEDIT2 = new ArrayList<Object>();
        }
        return this.jobOrSUBTABLEOrRULEBASEDCALENDARSOrTAGNAMESOrINCONDOrOUTCONDOrCONTROLOrAUTOEDITOrONGROUPOrONTABLEOrSHOUTOrAUTOEDIT2;
    }

}
