//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 07:29:59 PM CST 
//


package com.welch.xml.object;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@SuppressWarnings("restriction")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "TAG_NAMES")
public class TAGNAMES {

    @XmlAttribute(name = "TAG_NAME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tagname;

    /**
     * Gets the value of the tagname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAGNAME() {
        return tagname;
    }

    /**
     * Sets the value of the tagname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAGNAME(String value) {
        this.tagname = value;
    }

}
