CREATE OR REPLACE VIEW CTLM_V_IN_CONDITION
(
  JOB_NAME
, PARENT_JOB
, CHILD_JOB
, CONDITION_ORDER
, CONDITION_NAME
, AND_OR
, ODATE
, OP
)
AS
SELECT
  cic.JOB_NAME
, cic.PARENT_JOB
, cic.CHILD_JOB
, cic.CONDITION_ORDER
, CASE WHEN TYPE = 'G'
       THEN TYPE || SUBSTR(ct_p.DATACENTER,-2,2) || SUBSTR(ct_c.DATACENTER,-2,2) || '-' || cic.PARENT_JOB || '-' || cic.CHILD_JOB
       ELSE TYPE || '-' || cic.PARENT_JOB || '-' || cic.CHILD_JOB
  END
, cic.AND_OR
, cic.ODATE
, cic.OP
FROM CTLM_IN_CONDITION cic
INNER JOIN CTLM_JOB cj_p
   ON cic.PARENT_JOB = cj_p.JOBNAME
INNER JOIN CTLM_TABLE ct_p
   ON cj_p.PARENT_TABLE = ct_p.TABLE_NAME
INNER JOIN CTLM_JOB cj_c
   ON cic.CHILD_JOB = cj_c.JOBNAME
INNER JOIN CTLM_TABLE ct_c
   ON cj_c.PARENT_TABLE = ct_c.TABLE_NAME
;
