CREATE OR REPLACE VIEW CTLM_V_OUT_CONDITION
(
  ACTION_DETAIL_ID
, JOB_NAME
, PARENT_JOB
, CHILD_JOB
, CONDITION_NAME
, ODATE
, SIGN
)
AS
SELECT
  coc.ACTION_DETAIL_ID
, coc.JOB_NAME
, coc.PARENT_JOB
, coc.CHILD_JOB
, CASE WHEN TYPE = 'G'
       THEN TYPE || SUBSTR(ct_p.DATACENTER,-2,2) || SUBSTR(ct_c.DATACENTER,-2,2) || '-' || coc.PARENT_JOB || '-' || coc.CHILD_JOB
       ELSE TYPE || '-' || coc.PARENT_JOB || '-' || coc.CHILD_JOB
  END
, coc.ODATE
, coc.SIGN
FROM CTLM_OUT_CONDITION coc
INNER JOIN CTLM_JOB cj_p
   ON coc.PARENT_JOB = cj_p.JOBNAME
INNER JOIN CTLM_TABLE ct_p
   ON cj_p.PARENT_TABLE = ct_p.TABLE_NAME
INNER JOIN CTLM_JOB cj_c
   ON coc.CHILD_JOB = cj_c.JOBNAME
INNER JOIN CTLM_TABLE ct_c
   ON cj_c.PARENT_TABLE = ct_c.TABLE_NAME
;
