ALTER TABLE CTLM_REMEDY
   ADD CONSTRAINT PK_CTLM_REMEDY PRIMARY KEY (ACTION_DETAIL_ID,DESCRIPTION,SUMMARY,URGENCY)
   USING INDEX
   NOVALIDATE;

ALTER TABLE CTLM_REMEDY MODIFY (DESCRIPTION         NOT NULL ENABLE);
ALTER TABLE CTLM_REMEDY MODIFY (SUMMARY             NOT NULL ENABLE);
ALTER TABLE CTLM_REMEDY MODIFY (URGENCY             NOT NULL ENABLE);
ALTER TABLE CTLM_REMEDY MODIFY (CREATED_TSMP        NOT NULL ENABLE);
ALTER TABLE CTLM_REMEDY MODIFY (CREATED_BY_NAME     NOT NULL ENABLE);

