ALTER TABLE CTLM_QUANTATIVE_RESOURCE
   ADD CONSTRAINT PK_CTLM_QUANTATIVE_RES PRIMARY KEY (JOB_NAME,NAME)
   USING INDEX
   NOVALIDATE;

ALTER TABLE CTLM_QUANTATIVE_RESOURCE MODIFY (NAME                NOT NULL ENABLE);
ALTER TABLE CTLM_QUANTATIVE_RESOURCE MODIFY (QUANT               NOT NULL ENABLE);
ALTER TABLE CTLM_QUANTATIVE_RESOURCE MODIFY (CREATED_TSMP        NOT NULL ENABLE);
ALTER TABLE CTLM_QUANTATIVE_RESOURCE MODIFY (CREATED_BY_NAME     NOT NULL ENABLE);

