ALTER TABLE CTLM_ACTION_DETAIL
   ADD CONSTRAINT PK_CTLM_ACTION_DETAIL PRIMARY KEY (ACTION_DETAIL_ID)
   USING INDEX
   NOVALIDATE;

ALTER TABLE CTLM_ACTION_DETAIL MODIFY (ACTION              NOT NULL ENABLE);
ALTER TABLE CTLM_ACTION_DETAIL MODIFY (CREATED_TSMP        NOT NULL ENABLE);
ALTER TABLE CTLM_ACTION_DETAIL MODIFY (CREATED_BY_NAME     NOT NULL ENABLE);
