ALTER TABLE CTLM_CONTROL_RESOURCE
   ADD CONSTRAINT PK_CTLM_CONTROL_RESOURCE PRIMARY KEY (JOB_NAME,NAME)
   USING INDEX
   NOVALIDATE;

ALTER TABLE CTLM_CONTROL_RESOURCE MODIFY (NAME                NOT NULL ENABLE);
ALTER TABLE CTLM_CONTROL_RESOURCE MODIFY (TYPE                NOT NULL ENABLE);
ALTER TABLE CTLM_CONTROL_RESOURCE MODIFY (CREATED_TSMP        NOT NULL ENABLE);
ALTER TABLE CTLM_CONTROL_RESOURCE MODIFY (CREATED_BY_NAME     NOT NULL ENABLE);
