ALTER TABLE CTLM_ACTION
   ADD CONSTRAINT PK_CTLM_ACTION PRIMARY KEY (JOB_NAME,CODE)
   USING INDEX
   NOVALIDATE;

ALTER TABLE CTLM_ACTION MODIFY (ACTION_ID           UNIQUE ENABLE);
ALTER TABLE CTLM_ACTION MODIFY (CODE                NOT NULL ENABLE);
ALTER TABLE CTLM_ACTION MODIFY (CREATED_TSMP        NOT NULL ENABLE);
ALTER TABLE CTLM_ACTION MODIFY (CREATED_BY_NAME     NOT NULL ENABLE);

