ALTER TABLE CTLM_FORCE_JOB
   ADD CONSTRAINT PK_CTLM_FORCE_JOB PRIMARY KEY (ACTION_DETAIL_ID)
   USING INDEX
   NOVALIDATE;

ALTER TABLE CTLM_FORCE_JOB MODIFY (TABLE_NAME          NOT NULL ENABLE);
ALTER TABLE CTLM_FORCE_JOB MODIFY (ODATE               NOT NULL ENABLE);
ALTER TABLE CTLM_FORCE_JOB MODIFY (CREATED_TSMP        NOT NULL ENABLE);
ALTER TABLE CTLM_FORCE_JOB MODIFY (CREATED_BY_NAME     NOT NULL ENABLE);
