ALTER TABLE CTLM_GROUP
   ADD CONSTRAINT PK_CTLM_GROUP PRIMARY KEY (GROUP_NAME)
   USING INDEX
   NOVALIDATE;

ALTER TABLE CTLM_GROUP MODIFY (GROUP_NAME          NOT NULL ENABLE);
ALTER TABLE CTLM_GROUP MODIFY (ACTIVE_FLAG         NOT NULL ENABLE);
ALTER TABLE CTLM_GROUP MODIFY (CREATED_TSMP        NOT NULL ENABLE);
ALTER TABLE CTLM_GROUP MODIFY (CREATED_BY_NAME     NOT NULL ENABLE);
