ALTER TABLE CTLM_AUTO_EDIT_VARIABLE ADD CONSTRAINT check_auto_edit_variable
CHECK (JOB_NAME IS NOT NULL OR ACTION_DETAIL_ID IS NOT NULL);

ALTER TABLE CTLM_AUTO_EDIT_VARIABLE MODIFY (NAME                NOT NULL ENABLE);
ALTER TABLE CTLM_AUTO_EDIT_VARIABLE MODIFY (CREATED_TSMP        NOT NULL ENABLE);
ALTER TABLE CTLM_AUTO_EDIT_VARIABLE MODIFY (CREATED_BY_NAME     NOT NULL ENABLE);
