ALTER TABLE CTLM_OUT_CONDITION
   ADD CONSTRAINT PK_CTLM_OUT_CONDITION PRIMARY KEY (ACTION_DETAIL_ID,JOB_NAME,PARENT_JOB,CHILD_JOB,SIGN)
   USING INDEX
   NOVALIDATE;

ALTER TABLE CTLM_OUT_CONDITION MODIFY (ACTION_DETAIL_ID    NOT NULL ENABLE);
ALTER TABLE CTLM_OUT_CONDITION MODIFY (JOB_NAME            NOT NULL ENABLE);
ALTER TABLE CTLM_OUT_CONDITION MODIFY (PARENT_JOB          NOT NULL ENABLE);
ALTER TABLE CTLM_OUT_CONDITION MODIFY (CHILD_JOB           NOT NULL ENABLE);
ALTER TABLE CTLM_OUT_CONDITION MODIFY (ODATE               NOT NULL ENABLE);
ALTER TABLE CTLM_OUT_CONDITION MODIFY (SIGN                NOT NULL ENABLE);
ALTER TABLE CTLM_OUT_CONDITION MODIFY (CREATED_TSMP        NOT NULL ENABLE);
ALTER TABLE CTLM_OUT_CONDITION MODIFY (CREATED_BY_NAME     NOT NULL ENABLE);
