ALTER TABLE CTLM_SHOUT
   ADD CONSTRAINT PK_CTLM_SHOUT PRIMARY KEY (UUID)
   USING INDEX
   NOVALIDATE;
   
ALTER TABLE CTLM_SHOUT MODIFY (JOB_NAME            NOT NULL ENABLE);
ALTER TABLE CTLM_SHOUT MODIFY (DEST                NOT NULL ENABLE);
ALTER TABLE CTLM_SHOUT MODIFY (URGENCY             NOT NULL ENABLE);
ALTER TABLE CTLM_SHOUT MODIFY (CREATED_TSMP        NOT NULL ENABLE);
ALTER TABLE CTLM_SHOUT MODIFY (CREATED_BY_NAME     NOT NULL ENABLE);
