CREATE TABLE CTLM_QUANTATIVE_RESOURCE
(
  JOB_NAME                      VARCHAR2(100)
, NAME                          VARCHAR2(100)
, QUANT                         NUMBER
, CREATED_TSMP                  DATE
, CREATED_BY_NAME               VARCHAR2(30)
, AMENDED_TSMP                  DATE
, AMENDED_BY_NAME               VARCHAR2(30)
) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255
  NOCOMPRESS LOGGING;
