CREATE TABLE CTLM_ACTION
(
  ACTION_ID                     NUMBER
, JOB_NAME                      VARCHAR2(100)
, CODE                          VARCHAR2(100)
, STMT                          VARCHAR2(100)
, CREATED_TSMP                  DATE
, CREATED_BY_NAME               VARCHAR2(30)
, AMENDED_TSMP                  DATE
, AMENDED_BY_NAME               VARCHAR2(30)
) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255
  NOCOMPRESS LOGGING;
