CREATE TABLE CTLM_SYSOUT
(
  ACTION_DETAIL_ID              NUMBER
, SYSOUT_OPTION                 VARCHAR2(100)
, PAR                           VARCHAR2(100)
, CREATED_TSMP                  DATE
, CREATED_BY_NAME               VARCHAR2(30)
, AMENDED_TSMP                  DATE
, AMENDED_BY_NAME               VARCHAR2(30)
) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255
  NOCOMPRESS LOGGING;
