CREATE TABLE CTLM_FORCE_JOB
(
  ACTION_DETAIL_ID              NUMBER
, NAME                          VARCHAR2(100)
, ODATE                         VARCHAR2(100)
, TABLE_NAME                    VARCHAR2(30)
, CREATED_TSMP                  DATE
, CREATED_BY_NAME               VARCHAR2(30)
, AMENDED_TSMP                  DATE
, AMENDED_BY_NAME               VARCHAR2(30)
) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255
  NOCOMPRESS LOGGING;
