CREATE TABLE CTLM_REMEDY
(
  ACTION_DETAIL_ID              NUMBER
, DESCRIPTION                   VARCHAR2(100)
, SUMMARY                       VARCHAR2(100)
, URGENCY                       VARCHAR2(100)
, CREATED_TSMP                  DATE
, CREATED_BY_NAME               VARCHAR2(30)
, AMENDED_TSMP                  DATE
, AMENDED_BY_NAME               VARCHAR2(30)
) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255
  NOCOMPRESS LOGGING;
